PROJECT_NAME = "DJWOMS - Blog FastAPI"
SERVER_HOST = 'http://127.0.0.1:8000'

# Data Base
POSTGRES_SERVER = "localhost"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "123456"
POSTGRES_DB = "fastblog"

# Email
SMTP_TLS = True
SMTP_PORT = 587
SMTP_HOST = 'smtp.gmail.com'
SMTP_USER = 'djangosc876@gmail.com'
SMTP_PASSWORD = "F00dz!#0"
EMAILS_FROM_EMAIL = "djangosc876@gmail.com"
EMAILS_FROM_NAME = "DJWOMS - Blog FastAPI"
EMAIL_RESET_TOKEN_EXPIRE_HOURS = 48
EMAIL_TEMPLATES_DIR = "/src/email-templates/build"
EMAILS_ENABLED = SMTP_HOST and SMTP_PORT and EMAILS_FROM_EMAIL
